[project]
name = "Hohonu_QARTOD"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
start = "streamlit run src/app.py"

[dependencies]
streamlit = ">=1.45.0,<2"
pydantic = ">=2.11.3,<3"
ioos_qc = ">=2.2.0,<3"
pandas = ">=2.2.3,<3"
bokeh = "<=2.4.3"
pyyaml = ">=6.0.2,<7"
erddapy = ">=2.2.4,<3"
numpy = "<2"
