[project]
name = "Hohonu_QARTOD"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
start = "streamlit run src/app.py"

[dependencies]
streamlit = ">=1.37.1,<1.38"
pydantic = ">=2.8.2,<2.9"
pyyaml = ">=6.0.2,<6.1"
ioos_qc = ">=2.1.0,<2.2"
pandas = ">=2.2.2,<2.3"
bokeh = ">=3.5.1,<3.6"
